export enum EntityName {
  SupplierDocs = 'supplier_docs',
  Payment = 'payment',
  Order = 'order',
  OrderItem = 'order_item',
  MenuType = 'menu_type',
  Menu = 'menu',
  Discount = 'discount',
  Category = 'category',
  Supplier = 'supplier',
  SupplierOTP = 'supplier_otp',
  User = 'user',
  Address = 'user_address',
  OTP = 'otp',
  Feedback = 'feedback',
  Basket = 'basket',
}
